# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN \
    if [ $(command -v apt-get) ]; then \
        apt-get update \
        && apt-get install -y python sudo bash ca-certificates \
        && apt-get clean; \
    fi
RUN \
    if [ $(command -v dnf) ]; then \
        if [ $(cat /etc/redhat-release) == *"release 8"* ]; then \
            pkgs="python36 python36-devel python3-dnf"; \
        else \
            pkgs="python python-devel python2-dnf"; \
        fi \
        && dnf makecache \
        && dnf --assumeyes install sudo bash "${pkgs}" \
        && dnf clean all; \
    fi
RUN \
    if [ $(command -v yum) ]; then \
        if [ $(cat /etc/redhat-release) == *"release 8"* ]; then \
            pkgs="python36 python36-devel"; \
        else \
            pkgs="python python-devel"; \
        fi \
        && yum makecache fast \
        && yum install -y sudo yum-plugin-ovl bash \
        && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf \
        && yum clean all; \
    fi
RUN \
    if [ $(command -v zypper) ]; then \
        zypper refresh \
        && zypper install -y python sudo bash python-xml \
        && zypper clean -a; \
    fi
RUN \
    if [ $(command -v apk) ]; then \
        apk update \
        && apk add --no-cache python sudo bash ca-certificates; \
    fi
RUN \
    if [ $(command -v xbps-install) ]; then \
        xbps-install -Syu \
        && xbps-install -y python sudo bash ca-certificates \
        && xbps-remove -O; \
    fi
